### ISSUE TITLE
update favicons

### ISSUE THREAD

**Issue by Arhell** [nestjs/nestjs.com#33]
https://realfavicongenerator.net/favicon_checker?protocol=https&site=nestjs.com%2F#.YBnDVugzaMo

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Arhell** [comment]
> Would you like to create a PR for this issue?

Yes

**Comment by kamilmysliwiec** [comment]
Would you like to create the same PR for the documentation? https://github.com/nestjs/docs.nestjs.com @Arhell 💪
