### ISSUE TITLE
Wrong redisStore cache documentation

### ISSUE THREAD

**Issue by rcmarc** [nestjs/nestjs.com#68]
In the [docs](https://docs.nestjs.com/techniques/caching#different-stores), it says that a redis store on the CacheModule must be set up like this:

```typescript
@Module({
  imports: [
    CacheModule.register<RedisClientOptions>({
      store: redisStore,

      // Store-specific configuration:
      socket: {
        host: 'localhost',
        port: 6379,
      },
      isGlobal: true
    }),
  ],
  controllers: [AppController],
})
```

but when the service is manually injected:

```typescript
constructor(@Inject(CACHE_MANAGER) private cacheManager: Cache) {}
```

it gives an instance of the In Memory Cache

I think this is a  documentation issue because when i set up the CacheModule in this way without the socket object:
```typescript
@Module({
  imports: [
    CacheModule.register({
      store: redisStore,
      host: 'localhost',
      port: 6379,
      isGlobal: true
    }),
  ],
  controllers: [AppController],
})
```

it works as expected.

This issue was reproduced with this environment:
* node: 16.14.2
* @nestjs/core: 8.1.1
* cache-manager: 3.6.1
* cache-manager-redis-store: 2.0.0

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
